import product1 from "../../../public/images/525eebd82dd31d96fd518e97e5234fe0_78eb7754-39e4-4adc-b66c-acbaa089bfe7.webp";
import tracks1 from "../../../public/images/pantTracks.png";
export const productData = [
  {
    id: "1",
    img: product1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "2",
    img: product1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "3",
    img: product1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "4",
    img: product1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "5",
    img: product1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
];
export const tracksData = [
  {
    id: "1",
    img: tracks1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "2",
    img: tracks1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "3",
    img: tracks1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "4",
    img: tracks1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "5",
    img: tracks1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
  {
    id: "6",
    img: tracks1,
    name: "Blue Oversized T-shirt",
    description: "Blue Oversized T-shirt",
    price: "$99.99",
    color: "white",
    size: ["M", "L", "S", "XL", "XXl"],
  },
];
